### ISSUE TITLE
repetitive...

### ISSUE THREAD

**Issue by epcodes** [epcodes/freemint#6]
Does anybody here have ideas for how to fix the repetitive code?

**Comment by srappaport93** [comment]
do you have a specific example?
Any time you have something like this:
a = 8
b = 8
c = 8
d = 8
e = 8

I'd rewrite like this:

piecesArray = [a, b, c, d, e]

for piece in piecesArray:
    piece = 8

**Comment by epcodes** [comment]
Ah okie.
