### ISSUE TITLE
Paradoxical

### ISSUE THREAD

**Issue by epcodes** [epcodes/freemint#7]
In the later parts of play.py, it seems that you will need to infinitely loop some things for this to work. Any suggestions would be appreciated.

TY
-EP

**Comment by epcodes** [comment]
@cadenclaussen @srappaport93

**Comment by srappaport93** [comment]
Try to describe specifically what you're accomplishing -  sounds like you might want a while loop here?
i.e. "do this thing" while a condition is met and stop when it isn't
or "do this thing" until a condition is met and stop when it is

Python doesn't have until loops (some languages do), but it's essentially the same as a while loop.

**Comment by epcodes** [comment]
Yeah, there was a bug about the pawn tables so that was why I wrote this. Closing this now.
